### ISSUE TITLE
Use zstd?

### ISSUE THREAD

**Issue by tych0** [project-stacker/stacker#112]
Newer versions of mksquashfs have zstd support, which decompresses much faster and thus will have better performance at runtime. We should investigate the consequences of switching to zstd.

**Comment by tych0** [comment]
I think this roughly looks like, `mksquashfs --help | grep zstd` to make sure mksquashfs supports zstd, then if it does just remembering to pass the right flags.

May also be an opportunity to switch to https://github.com/anuvu/squashfs although the libraries would need write support as well.

**Comment by tych0** [comment]
Actual container tooling should also support zstd for the most part now, so it may be interesting to switch for the tar layers as well.

**Comment by tristanm-cisco** [comment]
Where would one look for understanding if all meaningful container tooling supports zstd+tar?

**Comment by tych0** [comment]
Good question. I know for sure that some of our cisco-internal tooling will need to be updated, but then probably also things like umoci (which I believe does), skopeo (IIUC also does), and then whatever dockerd version is running on the various platforms also need to be checked.
