### ISSUE TITLE
add support for substitutions using a yaml file

### ISSUE THREAD

**Issue by kprav33n** [project-stacker/stacker#271]
Stacker supports substitutions using `--substitute` command line options. Some projects have stacker files with multiple substitutions. This makes the command line too verbose and the shell scripts around it complex. It would be nice to have a new flag like `--substitutions` that takes multiple yaml files, merge them with left to right associativity and batch substitute using the key value pairs from the merged document.

### subs1.yaml
```yaml
GO_VERSION: 1.18
PRODUCT_VERSION: 0.5.0
```

### subs2.yaml
```yaml
SANDBOX: /dev/shm/utopia
PRODUCT_VERSION: 0.6.0
```

When running

```
stacker build --substitutions subs1.yaml subs2.yaml ...
```

it should behave like

```
stacker build --substitute "GO_VERSION=1.18" --substitute "SANDOX=/dev/shm/utopia" --substitute "PRODUCT_VERSION=0.6.0" ...
```

**Comment by tych0** [comment]
IMO, we have abused this feature fairly hard internally, and I'm a little loathe to write more code to support future abuse. Can there really be *that* many things that need to be substituted? Anyway, I'd probably take a patch to do it, but it also seems like reducing the number of substitutions required to build something will increase reading comprehension of the stacker files generally.

**Comment by tych0** [comment]
That said, if I was going to do this, I'd probably do this as part of the `config:` directive in stacker.yaml, so that no arguments are required. Maybe like,

```
config:
    substitutions:
        - ../../subs.yaml
        - ../../subs2.yaml
```

**Comment by rchincha** [comment]
Added with cmdline args --substitute-file colocated with --substitute
