### ISSUE TITLE
error while unmarshalling stacker file (binds field)

### ISSUE THREAD

**Issue by shimish2** [project-stacker/stacker#301]
If I add a binds field in stacker file like this 

``` 
binds:
        - Source: test 
          Dest: test
```

I get this error 

```error: unknown run array type: map[interface {}]interface {}``` 

but if I use binds field like this it works fine

``` 
binds:
        - test -> test 
```

**Comment by darshilgit** [comment]
Seems like [this part of code](https://github.com/project-stacker/stacker/blob/e8e0df5c2cbed4ed3112c71b0f248caa0137a558/types/layer.go#L151) is assuming that it will be a string but it can be a struct with `Source` and `Dest` strings (basically of type [Bind](https://github.com/project-stacker/stacker/blob/e8e0df5c2cbed4ed3112c71b0f248caa0137a558/types/layer.go#L133)
