### ISSUE TITLE
RFE: Allow import to take destination path

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#41]
WIP: allow import to take destination path.

When using --substitute with a stacker file, I came across a stacker the desire to have a destination path on the import.

I had a stacker file that was using --substitute to get a directory 'import'ed.  But then we wanted to use the path to that directory inside the 'run' section.

Imagine that the default 'SCRIPTS_DIR' below is named '/path/to/scripts', and is expected to have a script named 'do-magic' in it.

    import:
     - ${{SCRIPTS_DIR}}
    run: |
      PATH=/stacker/scripts:$PATH
      echo "running your script"
      do-magic

That will all work well.

However, if we want to change the name of SCRIPTS_DIR to 'common-scripts' then we'd have to change the yaml in two otherwise unrelated places (import and /run).  It is also unclear from reading this yaml file where /scripts comes from at all.  It seems annoying at least that there is an expectation on the content of the 'SCRIPTS_DIR' variable (it must end in /scripts).

What I'm proposing for a fix here is instead:

    import:
      - ${{SCRIPTS_DIR}} -> /scripts

Then the /scripts string is present in the two places that it is used and updates to the value of SCRIPTS_DIR do not force changesto the 'run:' section.

**Comment by mikemccracken** [comment]
How about having the import entry be a dict?
```yaml
import:
    - /a/regular/file
    - { source: "/a/badly/named/f1l3", dest: "/a/better/name" }
```
Seems a little more in keeping with the rest of stacker, ie using yaml instead of making new syntax…

**Comment by tych0** [comment]
The only thing is I already fucked up and invented this new syntax for "binds", it's just that we don't really use it.

**Comment by smoser** [comment]
Right. I just followed existing implementation on binds.

There dictionary does make sense, though.

**Comment by tych0** [comment]
I'd be open to a dictionary, and just dropping the other sytnax support from binds too.

**Comment by smoser** [comment]
one thing that is nice with an array of strings versus a dictionary is the human friendly-ness. example:

    import:
      - http://your.example.com/my.tar.gz -> /download.tar.gz
      - my-local-dir/

versus:

    import:
      - {'source': 'http://your.example.com/my.tar.gz', 'dest': '/download.tar.gz'}
      - {'source': 'my-local-dir/'}

or alternatively this is less extensible and "forces" declaration of the target:

    import:
      /download.tar.gz: http://your.example.com/my.tar.gz
      /my-local-dir: my-local-dir

**Comment by mikemccracken** [comment]
oh right, because it's golang parsing this, we can't easily have an array of both strings and dicts, right?

**Comment by tych0** [comment]
On Mon, Jul 15, 2019 at 10:22:21AM -0700, Michael McCracken wrote:
> oh right, because it's golang parsing this, we can't easily have an array of both strings and dicts, right?

We can actually; I wrote a bunch of helpers (which is why we can do
both run: | ... and run: -, -) that smoser is using here.

I don't have a strong opinion either way.

**Comment by rchincha** [comment]
Import directives now take a "dest" arg.
