### ISSUE TITLE
add an overlay_dirs: yaml entry

### ISSUE THREAD

**Issue by tych0** [project-stacker/stacker#83]
There's a lot of patterns of:

```
import: foo
run: cp /stacker/foo /
```

or worse

```
import: foo
rsync --lots-of-rsync-options /stacker/foo /
```

If we could instead have stacker do that, it would remove the need for people to have rsync or cp in their filesystem, and also avoid them having to think about all the right rsync options to pass in, since we could just import things with the right permissions.

Indeed, overlay_dirs: could just be layers themselves that stacker would auto-generate before doing the build (still exposing them in the rfs, of course).

**Comment by tych0** [comment]
@mikemccracken suggests that this should be another url scheme option in apply: which seems reasonable.

**Comment by rchincha** [comment]
overlay_dirs is now supported as a directive.
